media:
  input: media
  output: /media

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: blog
    output: true
    index_file: posts.json
    fields:
      - name: title
        type: string
      - name: date
        type: date
      - name: body
        type: rich-text
